[default]
address = "0.0.0.0"
port = 8090
log_level = "normal"

[default.limits]
file = "15 MiB"
data-form = "15 MiB"
form = "15 MiB"
bytes = "15 MiB"
json = "1 MiB"

[default.secret_key]
secret_key = "lmao no"
